name: Bug / Fix
description: Something is broken or incorrect
title: "[Bug]: "
labels:
  - type/bug
  - status/needs-info
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is broken?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Minimal steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Environment / Context
      description: OS, version, commit hash, config, etc.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority/P0
        - priority/P1
        - priority/P2
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      options:
        - size/xs
        - size/s
        - size/m
        - size/l
        - size/xl
