name: Feature
description: New functionality or capability
title: "[Feature]: "
labels:
  - type/feature
  - status/needs-design
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What concrete problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the feature at a technical level.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is explicitly included and excluded?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches and why they were rejected.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority/P0
        - priority/P1
        - priority/P2
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      options:
        - size/xs
        - size/s
        - size/m
        - size/l
        - size/xl
